version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: lm-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-mongopassword}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-learning_manager}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      timeout: 20s
      retries: 10
      start_period: 40s

  mongo-express:
    image: mongo-express:1.0
    container_name: lm-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-mongopassword}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-mongopassword}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-express}
    depends_on:
      mongodb:
        condition: service_healthy

  mysql:
    image: mysql:8.0.36
    container_name: lm-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-@hyeau1477}
      MYSQL_DATABASE: ${DB_NAME:-lm_db_dev}
      MYSQL_USER: ${DB_USER:-lm-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-1q2w3e4r}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  mysql_data:
    driver: local

networks:
  default:
    name: learning-manager-network