spring:
  application:
    name: learning-manager
server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:}
  access-token:
    validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY:1800}

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true

logging:
  level:
    org.hibernate.sql: debug
    org.springframework.web: debug

jwt:
  secret: ${JWT_SECRET:learning-manager-dev-secret-key-for-development-only}
  access-token:
    validity-in-seconds: 3600  # 개발환경에서는 1시간


---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
logging:
  level:
    web: error
    sql: error

jwt:
  secret: ${JWT_SECRET:}
  access-token:
    validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY:1800}

