spring:
  application:
    name: learning-manager

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:learning-manager-default-secret-key-for-development-use-only}
  access-token:
    validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY:1800}
    issuer: ${JWT_ISSUER:lxm-default-api}
    audience: ${JWT_AUDIENCE:lxm-default-auth}
  password-reset-token:
    issuer: ${JWT_ISSUER:lxm-password-api}
    audience: ${JWT_AUDIENCE:lxm-password-auth}
    validity-in-seconds: ${JWT_PASSWORD_RESET_TOKEN_VALIDITY:300}

course:
  member:
    bulk:
      max-size: 100

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true

logging:
  level:
    org.hibernate.sql: debug
    org.springframework.web: debug

jwt:
  secret: ${JWT_SECRET:learning-manager-dev-secret-key-for-development-only}
  access-token:
    validity-in-seconds: 3600  # 개발환경에서는 1시간
    issuer: "lxm-dev-api"
    audience: "lxm-dev-auth"
  password-reset-token:
    issuer: "lxm-dev-api"
    audience: "lxm-dev-auth"
    validity-in-seconds: 300

course:
  member:
    bulk:
      max-size: 100

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
logging:
  level:
    web: error
    sql: error

jwt:
  secret: ${JWT_SECRET:}
  access-token:
    validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY:1800}
    issuer: "lxm-prod-api"
    audience: "lxm-prod-auth"
  password-reset-token:
    issuer: "lxm-prod-api"
    audience: "lxm-prod-auth"
    validity-in-seconds: 300

course:
  member:
    bulk:
      max-size: 100