@startuml

title 1.3 [P1] Password Reset - (1) 패스워드 초기화 요청 (패스워드 분실 시나리오)

actor "User (Guest)" as User
participant "PasswordController" as Controller
participant "PasswordService" as AppService
participant "MemberRepository" as Repository
participant "EmailSender" as EmailAdapter

User -> Controller: Request Password Reset
activate Controller

Controller -> AppService: requestPasswordReset
activate AppService
alt Email Not Found
    AppService --> Controller: ErrorResponse (404 Not Found)
    deactivate AppService
    Controller --> User: Error Code
    deactivate Controller
else Email Found

AppService -> Repository: findByAccountEmail
activate Repository
Repository --> AppService: member
deactivate Repository

AppService -> EmailAdapter: sendPasswordResetEmail
activate EmailAdapter
EmailAdapter --> AppService: (async)
deactivate EmailAdapter

AppService --> Controller: void
deactivate AppService

Controller --> User: 200 OK
deactivate Controller
end
@enduml