@startuml

title 1.3 [P1] Password Reset - (2) 새 비밀번호로 초기화 (패스워드 분실 시나리오)

actor "User (Guest)" as User
participant "PasswordController" as Controller
participant "MemberPasswordResetService" as AppService
participant "Account" as AccountDomain
participant "MemberRepository" as Repository
participant "PasswordEncoder" as Encoder

User -> Controller: Set New Password
activate Controller

Controller -> AppService: resetPassword
activate AppService
alt Invalid or Expired Reset Token
    AppService --> Controller: ErrorResponse (400 Bad Request or 404 Not Found)
    deactivate AppService
    Controller --> User: Error Code
    deactivate Controller
else Valid Reset Token

AppService -> Repository: findByAccountResetToken
activate Repository
Repository --> AppService: member
deactivate Repository

AppService -> AccountDomain: changePassword
activate AccountDomain
AccountDomain -> Encoder
activate Encoder
Encoder --> AccountDomain
deactivate Encoder
AccountDomain --> AppService
deactivate AccountDomain

AppService -> Repository: save(member)
activate Repository

Repository --> AppService

deactivate Repository

AppService --> Controller: void
deactivate AppService

Controller --> User: 200 OK
deactivate Controller
end
@enduml