@startuml

title 1.5 [P1] Password Change : 로그인한 사용자의 비밀번호 변경
note "TODO: 비밀번호 변경 기능 미구현 상태" as N1

actor "User (Member)" as User
participant "JwtAuthenticationFilter" as Filter
participant "MemberPasswordController" as Controller
participant "PasswordChangeService" as AppService
participant "MemberQueryRepository" as QueryRepo
participant "Member" as MemberDomain
participant "Account" as AccountDomain
participant "PasswordEncoder" as Encoder
participant "MemberCommandRepository" as CommandRepo

User -> Controller: PUT /api/v1/members/change-password
note left: with Authorization header
activate Controller

Controller -> AppService: changePassword(request)
note left: memberId is from AuthenticationContextHolder
activate AppService

AppService -> QueryRepo: findById(memberId)
activate QueryRepo
QueryRepo --> AppService: member
deactivate QueryRepo

AppService -> MemberDomain: findAccountByEmail(email)
activate MemberDomain
MemberDomain --> AppService: account
deactivate MemberDomain

AppService -> MemberDomain: changeAccountPassword(accountId, newPassword, encoder)
activate MemberDomain
note right
  - Checks if new password is same as old
  - Encodes new password
end note
MemberDomain -> Encoder: matches()
MemberDomain -> Encoder: encode()
deactivate MemberDomain

AppService -> CommandRepo: save(member)
activate CommandRepo
deactivate CommandRepo

AppService --> Controller: Response
deactivate AppService

Controller --> User: 200 OK
deactivate Controller

@enduml
