@startuml

title 1.5 [P1] Password Change : 로그인한 사용자의 비밀번호 변경 시나리오

actor "User (Member)" as User
participant "CredentialValidator" as Validator
participant "PasswordController" as Controller
participant "PasswordService" as AppService
participant "Account" as AccountDomain
participant "MemberRepository" as Repository
participant "PasswordEncoder" as Encoder

User -> Controller: Change Password
activate Validator
activate Controller
Validator --> User: 401 Unauthorized
deactivate Validator

Controller -> AppService: changePassword
activate AppService
alt Current Password Mismatch
    AppService --> Controller: ErrorResponse (400 Bad Request)
    deactivate AppService
    Controller --> User: Error Code
    deactivate Controller
else Current Password Match

AppService -> Repository: findByMemberIdAndAccountType
activate Repository
Repository --> AppService: member
deactivate Repository

AppService -> AccountDomain: verify
activate AccountDomain
AccountDomain --> AppService: true
deactivate AccountDomain

AppService -> AccountDomain: changePassword
activate AccountDomain
AccountDomain --> AppService
deactivate AccountDomain

AppService -> Repository: save(member)
activate Repository
Repository --> AppService
deactivate Repository

AppService --> Controller: void
deactivate AppService

Controller --> User: 200 OK
deactivate Controller

end
@enduml