@startuml

title 2.6 [P1] Curriculum Creation : 커리큘럼 생성

actor "User (Manager)" as User
participant "CredentialValidator" as Validator
participant "CourseController" as Controller
participant "CourseService" as AppService
participant "Course" as CourseDomain
participant "CourseRepository" as Repository

User -> Controller: Create Curriculum
activate Validator
activate Controller
Validator --> User: 401 Unauthorized
Validator --> User: 403 Forbidden
deactivate Validator

Controller -> AppService: addCurriculumToCourse
activate AppService

AppService -> Repository: findById
activate Repository
Repository --> AppService: course
deactivate Repository

AppService -> CourseDomain: addCurriculum
activate CourseDomain
CourseDomain --> AppService : ok
deactivate CourseDomain

AppService -> Repository: save
activate Repository
Repository --> AppService : ok
deactivate Repository

AppService --> Controller: CurriculumResponse
deactivate AppService

Controller --> User: 201 Created
deactivate Controller

@enduml